### ISSUE TITLE
Segfault during use of `sfizz_render`

### ISSUE THREAD

**Issue by michaelkaeppler** [sfztools/sfizz#1260]
When trying to convert the attached MIDI file with the [Salamander](http://freepats.zenvoid.org/Piano/SalamanderGrandPiano/SalamanderGrandPianoV3+20161209_44khz16bit.tar.xz) soundfont to WAV, `sfizz_render` crashes.

The used version was compiled from 6cd063da8c6973447b0f86b63100e2aa1f2b1d48 under Ubuntu Focal.

Backtrace:
```
0  __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:436
#1  0x00005555555e1e85 in sfz::copy<float> (output=..., input=...)
    at /home/michael/sfizz/src/sfizz/SIMDHelpers.h:540
#2  sfz::Voice::Impl::amplitudeEnvelope (this=this@entry=0x555555a59fe0, 
    modulationSpan=...) at /home/michael/sfizz/src/sfizz/Voice.cpp:900
#3  0x00005555555e554a in sfz::Voice::Impl::ampStageStereo (
    this=this@entry=0x555555a59fe0, buffer=...)
    at /home/michael/sfizz/src/sfizz/Voice.cpp:949
#4  0x00005555555e7e56 in sfz::Voice::renderBlock (
    this=this@entry=0x555555a1fbf8, buffer=...)
    at /home/michael/sfizz/src/sfizz/AudioSpan.h:209
#5  0x00005555555aae03 in sfz::Synth::renderBlock (this=<optimized out>, 
    buffer=...) at /home/michael/sfizz/src/sfizz/AudioSpan.h:209
#6  0x0000555555576fd8 in main (argc=8, argv=0x7fffffffdf68)
    at /home/michael/sfizz/src/./sfizz/AudioSpan.h:194
```

**Comment by michaelkaeppler** [comment]
[Elgar_From_Bavarian_Highlands_Lullaby-Alt.zip](https://github.com/sfztools/sfizz/files/14931026/Elgar_From_Bavarian_Highlands_Lullaby-Alt.zip)

**Comment by michaelkaeppler** [comment]
Same file works fine with the Win64-build shipped in release 1.2.3.

**Comment by GeoffreyPlitt** [comment]
@michaelkaeppler I love the potential of this project, but I'm not sure how active development is now. Have you had any success with getting a response from the developers?

**Comment by paulfd** [comment]
I don't have much time for it no, and I'm the main/sole maintainer these days. Some people use sfizz downstream though and can maybe help sometimes.

**Comment by paulfd** [comment]
What exact CPU/OS are you using? Typically such illegal instructions vary alot between CPUs...
